version: '3'

services:
  site:
    image: jekyll/jekyll:3.8.6
    command: jekyll serve
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
  build:
    image: jekyll/jekyll:3.8.6
    command: jekyll build
    volumes:
      - '$PWD:/srv/jekyll'
      - '$PWD/vendor/bundle:/usr/local/bundle'
    environment:
        - JEKYLL_ENV=production
